# Generated by Django 4.2.6 on 2023-10-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_myuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], help_text='Choose between Movie or Series', max_length=200)),
            ],
        ),
    ]
