# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_type_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ManyToManyField(null=True, to='base.category'),
        ),
    ]
