# Generated by Django 4.2.6 on 2023-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_room_category_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ManyToManyField(to='base.category'),
        ),
    ]
